apiVersion: v1
kind: Pod
metadata:
  name: docker
spec:
  containers:
  - name: docker
    image: "676894657875.dkr.ecr.us-west-2.amazonaws.com/slm-ami/dockers:2022.02"
    command: ["cat"]
    tty: true
    securityContext:
      privileged: true
      hostNetwork: true
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: dockersock
    allowedCapabilities:
      - NET_ADMIN
  volumes:
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock
  - name: busybox
    image: busybox
    command:
    - cat
    tty: true
    env:
    - name: CONTAINER_ENV_VAR
      value: busybox
  volumes:
  - name: sharedvolume
    emptyDir: {}
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock
